# Generated by Django 5.0.9 on 2024-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
