# Generated by Django 5.0.9 on 2024-09-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0013_alter_subscriptions_options_subscriptions_featured_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionprice",
            options={
                "ordering": ["subscription__order", "order", "featured", "-price"]
            },
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Features for pricing separated by new line",
                null=True,
            ),
        ),
    ]
